### ISSUE TITLE
Allow creating user defined form pages

### ISSUE THREAD

**Issue by feejin** [bigfork/silverstripe-userforms-tidying#2]
Enable deciding if pages can be created in config.

**Comment by baukezwaan** [comment]
@feejin if I'm not mistaken, this already works this way:

By default the creation of UserDefinedForm is allowed (unlike [the readme states](https://github.com/bigfork/silverstripe-userforms-tidying/blob/master/README.md?plain=1#L13)).

But you can enforce this behaviour by adding this to you app.yml:
```
# prevent creation of UserDefinedForm pages, only via Elemental blocks
SilverStripe\UserForms\Model\UserDefinedForm:
  extensions:
    - Bigfork\SilverstripeUserFormsTidying\Extensions\UserDefinedFormExtension
```

**Comment by lozcalver** [comment]
I’ve updated the readme so it’s now correct, thanks @baukezwaan
